// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:3875f978-3d56-44ab-a0fe-3b85bec2a8f3",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_ep2CchjHI",
    "aws_user_pools_web_client_id": "2hffj6q11j7saochjpsljk7c9",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://jcnbdpfknnhg3fewkeekkdbbf4.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
